apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-connect
  labels:
    # Cluster name set previously
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    # Kafka Connects internal topics used to store configuration, offsets or status
    - resource:
        type: group
        name: connect-cluster
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Write
    - resource:
        type: topic
        name: connect-cluster-configs
      operation: Create
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Write
    - resource:
        type: topic
        name: connect-cluster-status
      operation: Create
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Read
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Write
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Describe
    - resource:
        type: topic
        name: connect-cluster-offsets
      operation: Create
    - resource:
        type: group
        name: connect-cluster
      operation: Read
    # Outbox topic
    - resource:
        type: topic
        name: mysql.moviesdb.OutboxEvent
      operation: Read
    - resource:
        type: topic
        name: mysql.moviesdb.OutboxEvent
      operation: Describe
    - resource:
        type: topic
        name: mysql.moviesdb.OutboxEvent
      operation: Write
    - resource:
        type: topic
        name: mysql.moviesdb.OutboxEvent
      operation: Create
    # movies topic (for Debezium embedded example)
    - resource:
        type: topic
        name: movies
      operation: Read
    - resource:
        type: topic
        name: movies
      operation: Describe
    - resource:
        type: topic
        name: movies
      operation: Write
    - resource:
        type: topic
        name: movies
      operation: Create