apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.30
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: alex
        - name: MYSQL_DATABASE
          value: moviesdb
        - name: MYSQL_USER
          value: alex
        - name: MYSQL_PASSWORD
          value: alex
        ports:
        - containerPort: 3306
          name: mysql